document.write('<header>');
document.write('<ul class="menu">');
document.write('	<li class="noclick">Dr. DANce</li>');
document.write('	<li onclick="window.open(\'index.html\');">How can we exercise?</li>');
document.write('	<li onclick="window.open(\'why.html\');">Why should we exercise?</li>');
document.write('	<li onclick="window.open(\'how-much.html\');">How much should we exercise?</li>');
document.write('	<li style="float:right;" onclick="window.open(\'references.html\');">References</li>');
document.write('	<li class="dropdown" style="float:right;padding:0;">');
document.write('		<div class="dropmain" onclick="window.open(\'about.html\');">About</div>');
document.write('		<div class="droprest" onclick="window.open(\'about-physicians.html\');">For physicians</div');
document.write('	</li>');
document.write('</ul>');
document.write('</header>');